### ISSUE TITLE
Please add new properties to adapter

### ISSUE THREAD

**Issue by xengosam** [iobroker-community-adapters/ioBroker.wled#15]
Hi @DutchmanNL,

seems like Aircoookie updated the API properties...

![image](https://user-images.githubusercontent.com/56436986/81494754-751b2e80-92ab-11ea-8891-1d12e576d940.png)

Can you implement them as well?

More Infos: https://github.com/Aircoookie/WLED/commit/94c5f0d7a8500e288578a001951bbc37db71d16d

Thank you for this gread Adapter!

Best regards,
xengosam

**Comment by DutchmanNL** [comment]
Yes sure I did plan it for this weekend but the weather was too beautiful

**Comment by copperfield74** [comment]
I have the same problem! Is there a fix on it's way?

Grüße

**Comment by drohne200** [comment]
I also have the problem

**Comment by xengosam** [comment]
@DutchmanNL should be fixed by #21

**Comment by DutchmanNL** [comment]
Yes good job by arteck but as mentioned to him already I need time to combine all the pull request, changes and updates in local sources to combine all code changes.

Expect to have that finished somewhere this week, last months due to private's reasons I was not able to take care of development but luckily time changes

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/f0c22ebabff53c48c707b210a6c35e94b968bec3
