### ISSUE TITLE
Make adapter ready to support WLED 0.10.2

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.wled#38]
**Describe wanted Enhancement !**  
Api error indicates new values with version 0.10.2, state attributes logic and propper values must be set

**Why should we put effort in it ?**  
Ensure support of newest firmware

**Additional context**  
Sentry messages : 

```
State attribute definition missing for + ws
State attribute definition missing for + mode
State attribute definition missing for + mi
```

**Comment by Aircoookie** [comment]
Hi, thank you for the reminder for documenting the new properties!

Here is a table of the new values (added to WLED JSON API wiki as well)

| JSON key | Value range | Description
| --- | --- | --- |
_info object_ | |
ws | -1 to 8 | Number of currently connected WebSockets clients. -1 indicates that WS is unsupported in this build.
_state object_ | |
nl.mode | 0 to 3 | Nightlight mode (0: instant, 1: fade, 2: color fade, 3: sunrise) (available since 0.10.2)
_segment object_ | | 
mi | bool | Mirrors the segment (available since 0.10.2)

**Comment by DutchmanNL** [comment]
> Here is a table of the new values (added to WLED JSON API wiki as well)
> 
> JSON key	Value range

Great thank you for your Swift response i will add it and Release a new Version ☺️

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/e7e72ffdef6fea73a510bc921f4998d26611e19b
