### ISSUE TITLE
Ab Version 0.5.0 funktioniert der Adapter nicht mehr

### ISSUE THREAD

**Issue by Stormbringer11** [iobroker-community-adapters/ioBroker.wled#44]
Hallo Dutchmann,

leider funktionieren die aktuelleren Versionen vom WLED Adapter bei mir nicht mehr richtig.
Anscheinend bekommt der Adapter weder mit welcher Effekt / Farbschema gerade beim NodeMCU abläuft noch kann er einen Befehl senden. 

Version 0.5.0 funktioniert hingegen einwandfrei sogar mit WLED Firmware 0.10.2

Fairnesshalber muss ich dazu sagen, dass ich tagsüber die WLED stromlos mache. Kann es sein, dass damit die Versionen über 0.5.0 ein Problem damit haben?

Falls du noch irgendwelche Sachen benötigst liefere ich die dir natürlich gerne. Vielen Dank :o)

**Comment by DutchmanNL** [comment]
hmm interessant, bis af die Abhängigkeiten hat sich code-technisch nichts geändert.
Eventueel laeuft die NodeMcu gegen out of memoir an durch die API abfragen ich arbeite noch daran https://github.com/iobroker-community-adapters/ioBroker.wled/pull/9 zu integrieren

**Comment by DocGame69** [comment]
Bei mir das selbe. Es wird weder ein Gerät gefunden (waren vorher schon da und integriert), noch kann ich sie über IP reinbringen.
Ein Downgrade von 0.54 auf 0.5 und es klappt wieder.....
Irgendwas muss sich ja geändert haben.

**Comment by Heleklu** [comment]
Bei mir ist es das selbe. Bis Version 0.5.0 funktioniert alles einwandfrei. Wird jedoch ein update auf die neueste (0.5.2) Version gemacht, funktioniert gar nichts mehr. Keine Verbundg über den Adapter mit der Lampe. Sobald die verion wieder auf 0.5.0 ist funktioniert wieder alles

**Comment by DcFamas** [comment]
Hallo Dutch,
ist auch bei mir so

`

host.ioBroker | 2020-11-22 14:06:20.418 | info | instance system.adapter.wled.0 started with pid 32635
-- | -- | -- | --
host.ioBroker | 2020-11-22 14:05:50.387 | info | Restart adapter system.adapter.wled.0 because enabled
host.ioBroker | 2020-11-22 14:05:50.386 | info | instance system.adapter.wled.0 terminated with code 0 (NO_ERROR)
host.ioBroker | 2020-11-22 14:05:50.385 | error | Caught by controller[0]: State attribute definition missing for + ws
wled.0 | 2020-11-22 14:05:49.848 | info | (32061) Terminated (NO_ERROR): Without reason
wled.0 | 2020-11-22 14:05:49.846 | info | (32061) terminating
wled.0 | 2020-11-22 14:05:49.808 | info | (32061) cleaned everything up...
wled.0 | 2020-11-22 14:05:49.806 | error | at async Wled.onReady (/opt/iobroker/node_modules/iobroker.wled/main.js:49:3)
wled.0 | 2020-11-22 14:05:49.806 | error | at async Wled.tryKnownDevices (/opt/iobroker/node_modules/iobroker.wled/main.js:640:19)
wled.0 | 2020-11-22 14:05:49.806 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
wled.0 | 2020-11-22 14:05:49.806 | error | at Wled.readData (/opt/iobroker/node_modules/iobroker.wled/main.js:423:17)
wled.0 | 2020-11-22 14:05:49.806 | error | at Wled.create_state (/opt/iobroker/node_modules/iobroker.wled/main.js:699:11)
wled.0 | 2020-11-22 14:05:49.806 | error | at Wled.sendSentry (/opt/iobroker/node_modules/iobroker.wled/main.js:796:37)
wled.0 | 2020-11-22 14:05:49.806 | error | (32061) TypeError: Cannot read property 'captureException' of undefined
wled.0 | 2020-11-22 14:05:49.804 | error | (32061) unhandled promise rejection: Cannot read property 'captureException' of undefined
Unhandled | 2020-11-22 14:05:49.803 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
wled.0 | 2020-11-22 14:05:49.799 | info | (32061) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + ws
wled.0 | 2020-11-22 14:05:49.798 | warn | (32061) State attribute definition missing for + ws
wled.0 | 2020-11-22 14:05:49.060 | info | (32061) Try to contact : "WLED" on IP : 192.168.178.47
wled.0 | 2020-11-22 14:05:49.058 | info | (32061) Try to contact known devices
wled.0 | 2020-11-22 14:05:48.984 | info | (32061) starting. Version 0.5.2 in /opt/iobroker/node_modules/iobroker.wled, node: v12.19.1, js-controller: 3.1.6

`

Mit 0.5.0 funktioniert es tadellos. :)

**Comment by DutchmanNL** [comment]
version 0.5.5 komt demnaest mit. allen fixes
